name="Example: My App"
project_id="pwaa-demo"
short_name="MyApp"
# Optional project url that will be used in html meta tags
# project_url="https://example.com"
bg_color="black"
lib="wasm-bindgen"
# For production deploys
env="production"
wasm_path="target/wasm32-unknown-unknown/release/pwaa_demo.wasm"
# Uncomment these values for faster to compile development builds
# env="development"
# wasm_path="target/wasm32-unknown-unknown/debug/seed_app.wasm"
